import { PageHeader } from "@/components/ui/page-header";
import { apiFetch } from "@/lib/api/server";
import type { Customer, Product, Subscription } from "@/lib/api/types";

export default async function SubscriptionsPage() {
  const [subscriptions, customers, products] = await Promise.all([apiFetch<Subscription[]>("/api/v1/subscriptions"), apiFetch<Customer[]>("/api/v1/customers"), apiFetch<Product[]>("/api/v1/products?limit=100")]);
  const customerMap = new Map(customers.map((item) => [item.id, item])); const productMap = new Map(products.map((item) => [item.id, item]));
  return <><PageHeader eyebrow="Recorrência" title="Assinaturas" description="Acompanhe ciclos, valores, renovações e cancelamentos." /><section className="overflow-hidden rounded-2xl border bg-surface shadow-panel">{subscriptions.length === 0 ? <p className="p-12 text-center text-sm text-muted">Nenhuma assinatura criada.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#fafafd] text-xs text-muted"><tr><th className="px-6 py-3 font-medium">Cliente</th><th className="px-6 py-3 font-medium">Produto</th><th className="px-6 py-3 font-medium">Valor</th><th className="px-6 py-3 font-medium">Status</th><th className="px-6 py-3 font-medium">Próxima cobrança</th></tr></thead><tbody className="divide-y">{subscriptions.map((subscription) => <tr key={subscription.id} className="text-sm"><td className="px-6 py-4 font-semibold">{customerMap.get(subscription.customerId)?.name ?? subscription.customerId}</td><td className="px-6 py-4 text-muted">{productMap.get(subscription.productId)?.name ?? subscription.productId}</td><td className="px-6 py-4 font-semibold">{new Intl.NumberFormat("pt-BR", { style: "currency", currency: subscription.currency }).format(subscription.amountMinor / 100)}/{interval(subscription.interval)}</td><td className="px-6 py-4"><span className="rounded-full bg-[#e8f7f1] px-2.5 py-1 text-xs font-semibold text-success">{subscription.status}</span></td><td className="px-6 py-4 text-muted">{subscription.nextBillingAt ? new Intl.DateTimeFormat("pt-BR").format(new Date(subscription.nextBillingAt)) : "—"}</td></tr>)}</tbody></table></div>}</section></>;
}
function interval(value: string) { return { day: "dia", week: "semana", month: "mês", year: "ano" }[value] ?? value; }
