import { PageHeader } from "@/components/ui/page-header";
import { apiFetch } from "@/lib/api/server";
import type { Customer, Payment } from "@/lib/api/types";

export default async function PaymentsPage() {
  const [payments, customers] = await Promise.all([apiFetch<Payment[]>("/api/v1/payments"), apiFetch<Customer[]>("/api/v1/customers")]);
  const customerById = new Map(customers.map((customer) => [customer.id, customer]));
  return <><PageHeader eyebrow="Financeiro" title="Vendas e pagamentos" description="Acompanhe as transações processadas pelos gateways conectados." /><section className="overflow-hidden rounded-2xl border bg-surface shadow-panel">{payments.length === 0 ? <p className="p-12 text-center text-sm text-muted">Nenhum pagamento processado.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#fafafd] text-xs text-muted"><tr><th className="px-6 py-3 font-medium">Pagamento</th><th className="px-6 py-3 font-medium">Cliente</th><th className="px-6 py-3 font-medium">Método</th><th className="px-6 py-3 font-medium">Valor</th><th className="px-6 py-3 font-medium">Status</th><th className="px-6 py-3 font-medium">Data</th></tr></thead><tbody className="divide-y">{payments.map((payment) => <tr key={payment.id} className="text-sm"><td className="px-6 py-4 font-mono text-xs">{payment.id}</td><td className="px-6 py-4"><p className="font-semibold">{customerById.get(payment.customerId)?.name ?? "Cliente"}</p><p className="text-xs text-muted">{customerById.get(payment.customerId)?.email}</p></td><td className="px-6 py-4 text-muted">{payment.paymentMethod}</td><td className="px-6 py-4 font-semibold">{money(payment.amountMinor, payment.currency)}</td><td className="px-6 py-4"><Status value={payment.status} /></td><td className="px-6 py-4 text-muted">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(payment.createdAt))}</td></tr>)}</tbody></table></div>}</section></>;
}
function money(value: number, currency: string) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(value / 100); }
function Status({ value }: { value: string }) { const good = ["approved", "paid", "captured", "succeeded"].includes(value); return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${good ? "bg-[#e8f7f1] text-success" : "bg-[#fff3e5] text-warning"}`}>{value}</span>; }
